# Generated by Django 5.1.4 on 2025-01-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relecloud", "0006_alter_cruise_subtitle_alter_destination_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(upload_to="uploads/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="destinations",
        ),
        migrations.RemoveField(
            model_name="inforequest",
            name="cruise",
        ),
        migrations.DeleteModel(
            name="Destination",
        ),
        migrations.DeleteModel(
            name="Cruise",
        ),
        migrations.DeleteModel(
            name="InfoRequest",
        ),
    ]
