name: Build and deploy Python app to Azure Web App - hoster

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip dependencies
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-prod.txt') }}  # Cache key based on requirements file
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Cache pip dependencies (before installation)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip cache to avoid downloading packages each time
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-prod.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create and start virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install dependencies (this is where the actual installation happens)
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements-prod.txt
          pip install azure-cli
          pip install azure-identity azure-keyvault-secrets

      # Cache virtual environment (after installation)
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: venv  # Cache the virtual environment after dependencies have been installed
          key: ${{ runner.os }}-python-${{ hashFiles('requirements-prod.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # Authenticate with Azure using service principal
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
      - name: Set Azure environmental variables
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "AZURE_CREDENTIALS=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV

      # - name: Fetch secrets from Azure Key Vault
      #   continue-on-error: false
      #   run: |
      #     echo "POSTGRES_PASSWORD=$(az keyvault secret show --name PGPW --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "POSTGRES_DB=$(az keyvault secret show --name PGDB --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "POSTGRES_HOST=$(az keyvault secret show --name PGH --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "POSTGRES_PORT=$(az keyvault secret show --name PGPORT --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "POSTGRES_SSL=$(az keyvault secret show --name PGSSL --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "POSTGRES_USER=$(az keyvault secret show --name PGUSER --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
      #     echo "AZURE_STORAGE_CONNECTION_STRING=$(az keyvault secret show --name PGUSER --vault-name hoster-secrets --query value -o tsv)" >> $GITHUB_ENV
          
      - name: Get Azure Key Vault Secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "hoster-secrets"  # Name of your key vault
          secrets: 'PGPW, PGDB, PGH, PGPORT, PGSSL, PGUSER, AZURE-STORAGE-CONNECTION-STRING'
        id: getazuresecrets

      - name: Set environment variables
        run: |
          echo "POSTGRES_PASSWORD=${{ steps.getazuresecrets.outputs.PGPW }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ steps.getazuresecrets.outputs.PGDB }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ steps.getazuresecrets.outputs.PGH }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ steps.getazuresecrets.outputs.PGPORT }}" >> $GITHUB_ENV
          echo "POSTGRES_SSL=${{ steps.getazuresecrets.outputs.PGSSL }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ steps.getazuresecrets.outputs.PGUSER }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ steps.getazuresecrets.outputs.AZURE-STORAGE-CONNECTION-STRING }}" >> $GITHUB_ENV

      # Run the create-prod-env.py script to generate .env.production file
      - name: Create production environment file
        run: |
          python scripts/create-prod-env.py

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          echo "Current directory contents:"
          ls -la
          
          echo "Creating deployment package..."
          zip release.zip ./* ./.* -r \
          -x "./venv/*" \
          -x "./.venv/*" \
          -x "./frontend/*" \
          -x "./infra/*" \
          -x "./node_modules/*" \
          -x "./.git/*" \
          -x "./__pycache__/*" \
          -x "./*.pyc" \
          -x "./tests/*"
          
          echo "Final zip contents:"
          unzip -l release.zip | grep -i "venv" # This will specifically show if venv is included
          echo "Full zip contents:"
          unzip -l release.zip

      - name: Check deployment package size
        run: ls -lh release.zip

      - name: Include additional deployment files
        run: |
          cp .env.production ./.env

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: |
            release.zip
            .env

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      
      - name: Set frontend environment variables
        run: |
          echo "VITE_BACKEND_URL=" >> $GITHUB_ENV

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload frontend bundle
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Verify App Service existence
      #   run: |
      #     az webapp show --name hoster --resource-group hoster
    
      - name: Unzip backend artifact
        run: unzip release.zip

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-backend
        with:
          app-name: 'hoster'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '.'
          verbose: true

      # Deploy frontend
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend

      - name: Upload frontend to Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload-batch \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key $AZURE_STORAGE_KEY \
            --destination '$web' \
            --source frontend/dist

      - name: Verify deployment
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.webapp-url }}"
          echo "Frontend URL : https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net"
