# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - hoster

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: |
            release.zip
            !venv/

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload frontend bundle
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Unzip backend artifact
        run: unzip release.zip

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-backend
        with:
          app-name: 'hoster'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_337529ED7DC34EE2895AC04F10880895 }}

      # Deploy frontend
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend

      - name: Upload frontend to Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload-batch \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key $AZURE_STORAGE_KEY \
            --destination '$web' \
            --source frontend/dist

      - name: Verify deployment
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.webapp-url }}"
          echo "Frontend URL: https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net"
